# Generated by Django 5.1.4 on 2025-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_inboxmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmessage',
            name='message',
            field=models.CharField(max_length=50000),
        ),
    ]
