# Generated by Django 5.1.4 on 2025-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_inboxmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmessage',
            name='message',
            field=models.CharField(max_length=5000000000),
        ),
    ]
