# Generated by Django 5.1.4 on 2025-05-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=150)),
                ('program', models.CharField(max_length=150)),
                ('year_of_study', models.IntegerField()),
                ('phone_no', models.TextField(max_length=11)),
            ],
        ),
    ]
