# Generated by Django 5.1.4 on 2025-05-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_of_study',
            field=models.IntegerField(null=True),
        ),
    ]
